experiment_dir: /data/paciorek/output_22y_40m_Feb1
n_forward_steps: 1286936
forward_steps_in_memory: 50
checkpoint_path: ace2_era5_ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace
initial_condition:
  path: initial_conditions/ic_2001.nc
  start_indices:
    times:
    - '2001-02-01T00:00:00'
forcing_loader:
  dataset:
    data_path: forcing_data
    n_repeats: 41
  num_data_workers: 2
data_writer:
  save_prediction_files: true
  save_monthly_files: false
  names:
  - TMP2m
  - PRATEsfc
